### ISSUE TITLE
Timeout issues with mochify@2.10.0. 2.9.0 works fine.

### ISSUE THREAD

**Issue by tjunghans** [mantoni/mochify.js#94] opened 2015-06-26 11:58 UTC
A large amount of test cases or complicated tests are causing the test-run to timeout with mochify@2.10.0. A **downgrade to 2.9.0 fixes the issue**.

In one case the tests running locally timeout with the following exception:
`timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.`

In another case selenium was reporting timeouts. The timeout can be reproduced reliably, however the number of test cases that run before the time out varies.

**Comment by mantoni** [comment] 2015-06-26 13:09
Can you isolate the issue into something reproducible?

**Comment by tjunghans** [comment] 2015-06-26 13:55
Sure, I'll try to whip something up.

**Comment by tjunghans** [comment] 2015-06-26 14:44
The error has no correlation with the number of test cases (it-statements) or assertions. There's also no correlation with the duration of the test-run. A dummy test-run with a duration of over 6 minutes, 100k it-statements doing DOM manipulation were no problem. The problem lies somewhere else. Still analyzing...

**Comment by mantoni** [comment] 2015-06-29 09:45
So it turns out to be `process.nextTick` that needs to be stubbed away. It's the one potentially breaking change in Browserify 10 that was causing the issue.
See https://github.com/substack/node-browserify/blob/master/changelog.markdown#1000
Closing.

**Closed by mantoni** 2015-06-29 09:45 UTC
