### ISSUE TITLE
Mochify tests don't share imports with application code?

### ISSUE THREAD

**Issue by rafalp** [mantoni/mochify.js#126] opened 2016-01-16 18:45 UTC
After updating my deps to latest versions my tests suite exploded due to ReactDOM imported in my app modules being different instance than one imported in test modules, thus breaking my tests.

It goes like this:

1. `/app/some-module` imports and uses ReactDOM to mount component.
2. `/tests/some-test`impots and uses ReactDOM to unmount component from test mount.

This code worked, but now it seems that those two places don't share ReactDOM instance anymore, meaning tests don't cleanup components anymore.

Here's traceback if I throw on ReactDOM's first import:

      at node_modules/react/lib/ReactMount.js:850
      at null:null
      at node_modules/mochify/node_modules/browser-pack/_prelude.js:1
      at node_modules/mochify/node_modules/browser-pack/_prelude.js:1
      at node_modules/react/lib/ReactDOMIDOperations.js:17
      at null:null
      at node_modules/mochify/node_modules/browser-pack/_prelude.js:1
      at node_modules/mochify/node_modules/browser-pack/_prelude.js:1
      at node_modules/react/lib/ReactComponentBrowserEnvironment.js:14
      at node_modules/mochify/node_modules/browser-pack/_prelude.js:1
      at node_modules/mochify/node_modules/browser-pack/_prelude.js:1
      at node_modules/react/lib/ReactDOMTextComponent.js:17
      at null:null
      at node_modules/mochify/node_modules/browser-pack/_prelude.js:1
      at node_modules/mochify/node_modules/browser-pack/_prelude.js:1
      at node_modules/react/lib/ReactDOM.js:17
      at null:null
      at node_modules/mochify/node_modules/browser-pack/_prelude.js:1
      at node_modules/mochify/node_modules/browser-pack/_prelude.js:1
      at node_modules/react-dom/index.js:3
      at node_modules/mochify/node_modules/browser-pack/_prelude.js:1
      at node_modules/mochify/node_modules/browser-pack/_prelude.js:1
      at src/test-setup.js:26
      at null:null
      at node_modules/mochify/node_modules/browser-pack/_prelude.js:1
      at node_modules/mochify/node_modules/browser-pack/_prelude.js:1

Here's one from second import:

      at ../../../documents/misago/frontend/node_modules/react/lib/ReactMount.js:851
      at null:null
      at node_modules/mochify/node_modules/browser-pack/_prelude.js:1
      at node_modules/mochify/node_modules/browser-pack/_prelude.js:1
      at ../../../documents/misago/frontend/node_modules/react/lib/ReactDOMIDOperations.js:17
      at null:null
      at node_modules/mochify/node_modules/browser-pack/_prelude.js:1
      at node_modules/mochify/node_modules/browser-pack/_prelude.js:1
      at node_modules/react/lib/ReactComponentBrowserEnvironment.js:14
      at null:null
      at node_modules/mochify/node_modules/browser-pack/_prelude.js:1
      at node_modules/mochify/node_modules/browser-pack/_prelude.js:1
      at ../../../documents/misago/frontend/node_modules/react/lib/ReactDOMTextComponent.js:17
      at null:null
      at node_modules/mochify/node_modules/browser-pack/_prelude.js:1
      at node_modules/mochify/node_modules/browser-pack/_prelude.js:1
      at ../../../documents/misago/frontend/node_modules/react/lib/ReactDOM.js:17
      at null:null
      at node_modules/mochify/node_modules/browser-pack/_prelude.js:1
      at node_modules/mochify/node_modules/browser-pack/_prelude.js:1
      at node_modules/react-dom/index.js:3
      at null:null
      at node_modules/mochify/node_modules/browser-pack/_prelude.js:1
      at node_modules/mochify/node_modules/browser-pack/_prelude.js:1
      at null:null
      at node_modules/mochify/node_modules/browser-pack/_prelude.js:1
      at node_modules/mochify/node_modules/browser-pack/_prelude.js:1
      at null:null
      at node_modules/mochify/node_modules/browser-pack/_prelude.js:1
      at node_modules/mochify/node_modules/browser-pack/_prelude.js:1

Here's setup I'm currently using:

https://github.com/rafalp/Misago/commit/8503e0253b13d54c11712323b23c05dc506b8800

- - - -

I'm currently planning to move some of my tests utils into ES6 module under app's namespace to see if this will fix the tests suite, but still such sudden change of behaviour is eyebrow raising. (**edit 5 mins later:** yep that fixed it)

Still, I want it to be noted that **I DONT** "blame: Mochify. I am still too unexperienced in Node Fu to pinpoint exact reason. I'm writing here as this is simply best bet I have so far, but there may be chance that this was caused by update in other part of stack, eg. Babel or Browserify.

Still, I appreciate your time any potential pointers or wisdom on the matter.

**Comment by mantoni** [comment] 2016-01-16 21:27
Check if you have ReactDOM in your dependencies more than once. You can use `npm ls {module-name}` for this. If it's there twice, instanceof checks may fail and singletons may exist multiple times. To fix this, you can either run `npm dedupe`, or remove the `node_modules` folder and the `npm install` your dependencies freshly.

Note: while npm 3 installs "deduped" by default, npm 2 does not.

Let me know if this fixes the issue for you.

**Comment by rafalp** [comment] 2016-01-16 21:47
I can confirm I have React-DOM installed only once, I'm on npm 3 and I've reinstalled my node_modules before reporting.

**Comment by mantoni** [comment] 2016-01-16 22:45
Hm, that sounds weird. There is certainly a lot of variables there and I'm not familiar with all your dependencies. It'll take a while until I can try to reproduce with your project. It would be great if you could narrow it down a little more.

**Comment by mantoni** [comment] 2016-07-13 08:26
Closing as this does not seem to be related to Mochify itself.

**Closed by mantoni** 2016-07-13 08:26 UTC
